services:
  - type: web
    name: thinkboard-backend
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
